
package uy.edu.cure.servidor.web.javafromwdsl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloWSImpl", targetNamespace = "http://server.soap.webapp.central.servidor.cure.edu.uy", wsdlLocation = "file:/E:/PrAp/proyecto/servidor-central/servidor-central-webapp/src/main/java/uy/edu/cure/servidor/central/webapp/soap/server/HelloWSImpl.wsdl")
public class HelloWSImpl
    extends Service
{

    private final static URL HELLOWSIMPL_WSDL_LOCATION;
    private final static WebServiceException HELLOWSIMPL_EXCEPTION;
    private final static QName HELLOWSIMPL_QNAME = new QName("http://server.soap.webapp.central.servidor.cure.edu.uy", "HelloWSImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/E:/PrAp/proyecto/servidor-central/servidor-central-webapp/src/main/java/uy/edu/cure/servidor/central/webapp/soap/server/HelloWSImpl.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOWSIMPL_WSDL_LOCATION = url;
        HELLOWSIMPL_EXCEPTION = e;
    }

    public HelloWSImpl() {
        super(__getWsdlLocation(), HELLOWSIMPL_QNAME);
    }

    public HelloWSImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOWSIMPL_QNAME, features);
    }

    public HelloWSImpl(URL wsdlLocation) {
        super(wsdlLocation, HELLOWSIMPL_QNAME);
    }

    public HelloWSImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOWSIMPL_QNAME, features);
    }

    public HelloWSImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWSImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloWS
     */
    @WebEndpoint(name = "HelloWSImpl")
    public HelloWS getHelloWSImpl() {
        return super.getPort(new QName("http://server.soap.webapp.central.servidor.cure.edu.uy", "HelloWSImpl"), HelloWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWS
     */
    @WebEndpoint(name = "HelloWSImpl")
    public HelloWS getHelloWSImpl(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.soap.webapp.central.servidor.cure.edu.uy", "HelloWSImpl"), HelloWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWSIMPL_EXCEPTION!= null) {
            throw HELLOWSIMPL_EXCEPTION;
        }
        return HELLOWSIMPL_WSDL_LOCATION;
    }

}
